mydjango04/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("profile/edit/", views.profile_edit, name="profile_edit"),
    path("profile/wizard/", views.profile_wizard, name="profile_wizard"),
    path("login/", views.login, name="login"),
    path("profile/", views.profile, name="profile"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.logout, name="logout"),
    path("password_change/", views.password_change, name="password_change"),
    path("password_reset/", views.password_reset, name="password_reset"),
    path(
        "reset/<uidb64>/<token>/",
        views.password_reset_confirm,
        name="password_reset_confirm",
    ),
]

mydjango04/accounts/templates/accounts/login_form.html
{% comment %}
<form action="" method="post" novalidate>
    {% csrf_token %}
    <input type="text" name="username" />
    <input type="password" name="password" />
    <input type="submit" />
</form>
{% endcomment %}

<form action="" method="post" novalidate>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

mydjango04/accounts/templates/accounts/password_change_form.html
<form action="" method="post" novalidate>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

mydjango04/accounts/templates/accounts/password_reset_email.html
{% extends "registration/password_reset_email.html" %}

{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

mydjango04/accounts/templates/accounts/profile_form.html
<style>
  form#django-form table { border-collapse: collapse; }
  form#django-form th, td { border: 1px solid black; padding: 5px; }
  form#django-form .errorlist { color: red; padding: 0; margin: 0; font-size: .5em; }
  form#django-form .errorlist li { list-style-type: none; }
</style>

{{ profile_user_form.media }}
{{ profile_form.media }}

<h2>프로필 수정 폼</h2>

<form id="django-form" action="" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    <table>
        {{ profile_user_form.as_table }}
        {{ profile_form.as_table }}
    </table>
    <input type="submit" />
</form>

mydjango04/accounts/templates/accounts/profile_wizard.html
{# accounts/templates/accounts/profile_wizard.html #}

<body>
{% if messages %}
    {% for message in messages %}
        {{ message }}<br/>
    {% endfor %}
{% endif %}

{{ wizard.form.media }}

<p>{{ wizard.steps.count }}단계 중 {{ wizard.steps.step1 }}단계</p>

<form action="" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}

    {# 마법사 관리 정보 - hidden: current_step #}
    {{ wizard.management_form }}

    {% if wizard.form.forms %}
        {# formset 대응 #}
        {{ wizard.form.management_form }}
        {% for form in wizard.form.forms %}
            <table>
                {{ form.as_table }}
            </table>
        {% endfor %}
    {% else %}
        {# form 대응 #}
        <table>{{ wizard.form.as_table }}</table>
    {% endif %}

    {% if wizard.steps.prev %}
        <button name="wizard_goto_step" type="submit"
                value="{{ wizard.steps.first }}">
            처음 단계
        </button>
        <button name="wizard_goto_step" type="submit"
                value="{{ wizard.steps.prev }}">
            이전 단계
        </button>
    {% endif %}

    <input type="submit" value="다음" />
</form>
</body>

mydjango04/accounts/templates/accounts/signup_form.html
<form action="" method="post" novalidate>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>