mydjango04/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("posts/", views.post_list, name="post_list"),
    path("posts/new/", views.post_new, name="post_new"),
    path("posts/search/", views.search, name="search"),
    path(
        "posts/premium-user-guide/", views.premium_user_guide, name="premium_user_guide"
    ),
    path(
        "posts/premium/<str:slug>/",
        views.post_premium_detail,
        name="post_premium_detail",
    ),
    path("posts/<str:slug>/", views.post_detail, name="post_detail"),
    path("reviews/", views.review_list, name="review_list"),
    path("reviews/new/", views.review_new, name="review_new"),
    path("reviews/<int:pk>/", views.review_detail, name="review_detail"),
    path("reviews/<int:pk>/edit/", views.review_edit, name="review_edit"),
    path("demo/", views.demo_form),
    path("memogroup/<int:group_pk>/form/", views.memo_form, name="memo_form"),
    path("tags/", views.tag_list, name="tag_list"),
    path("tags/new/", views.tag_new, name="tag_new"),
    path("tags/<int:pk>/edit/", views.tag_edit, name="tag_edit"),
    path("tags/<int:pk>/delete/", views.tag_delete, name="tag_delete"),
    path("tags/item/<int:pk>/", views.tag_list_item, name="tag_list_item"),
    path("test/", views.test, name="test"),
]

mydjango04/blog/templates/blog/_tag_form.html
{# blog/templates/blog/_tag_form.html : HTML 레이아웃없이 컨텐츠로만 구성 #}

{% load component_tags django_bootstrap5 partials %}

{% include "core/_messages_as_event.html" %}

{% partialdef tag-form %}
    <form hx-post="{{ request.get_full_path }}"
          hx-trigger="submit once"
          hx-swap="outerHTML"
          autocomplete="off"
          novalidate>
        {% csrf_token %}
        {% bootstrap_form form %}
        {# <input type="submit" class="btn btn-primary"/> #}
    </form>
{% endpartialdef %}

{% if request.method == "POST" %}
    {% partial tag-form %}
{% else %}
    {% component "modal-form" id="tag-form" %}
        {% fill "modal-title" %}
            {% if not form.instance.pk %}태그 생성{% else %}태그 수정{% endif %}
        {% endfill %}
        {% fill "modal-body" %}
            {% partial tag-form %}
        {% endfill %}
    {% endcomponent %}
    <script>
      (function() {
        const modalEl = document.currentScript.previousElementSibling;

        // refresh-tag-list 이벤트를 받으면 모달창을 닫습니다.
        document.body.addEventListener("refresh-tag-list", function () {
          htmx.trigger(modalEl, "hide");
        });
      })();
    </script>
{% endif %}

mydjango04/blog/templates/blog/_tag_list_item.html
{% include "core/_messages_as_event.html" %}

<div class="list-group-item d-flex justify-content-between align-items-center">
    <div
            style="cursor: pointer;"
            hx-get="{% url 'blog:tag_edit' tag.pk %}"
            hx-trigger="click"
            hx-target="#modal-container"
            hx-swap="innerHTML"
    >
        {{ tag.name }}
    </div>
    <span
            class="text-danger"
            style="cursor: pointer;"
            hx-trigger="click"
            hx-confirm="{{ tag.name }} 태그를 삭제하시겠습니까?"
            hx-delete="{% url 'blog:tag_delete' tag.pk %}"
            hx-target="closest .list-group-item"
            hx-swap="delete"
    >
            X
        </span>
</div>

mydjango04/blog/templates/blog/base.html
{# blog/templates/blog/base.html #}

{% load component_tags django_bootstrap5 static %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8"/>
    <title>{% block title %}{% endblock %}</title>
    {% bootstrap_css %}
    {% component_css_dependencies %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/htmx/1.9.10/htmx.min.js"></script>
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
<main style="width: 400px; margin: 1em;">
    <h1>유저: {{ request.user }}</h1>
    {% block content %}{% endblock %}
</main>

{# Modal이 위치할 요소를 먼저 정의합니다. #}
<div id="modal-container"></div>

<script>
document.body.addEventListener('htmx:configRequest', function (event) {
  const htmxElement = event.detail.elt;
  const isGetRequest = htmxElement.hasAttribute('hx-get');
  if ( isGetRequest && htmxElement.hasAttribute('hx-get-with-timestamp') ) {
    const paramName = htmxElement.getAttribute('hx-get-with-timestamp') || '_';
    event.detail.parameters[paramName] = new Date().getTime();
  }
});
</script>
{% bootstrap_javascript %}
{% component_js_dependencies %}
<script src="{% static 'core/toast-messages.js' %}"></script>
{% include "core/_messages_as_event.html" %}
{% block extra-script %}{% endblock %}
</body>
</html>

mydjango04/blog/templates/blog/demo_form.html
{% load crispy_forms_tags %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"/>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"></script>

<div class="container my-3">
{#    <form action="" method="post" novalidate>#}
        {% crispy form form.helper %}
{#    </form>#}
</div>

mydjango04/blog/templates/blog/demo_form_field.html
{# blog/demo_form_field.html #}

{% load widget_tweaks %}

<div class="my-2">
    {# 각 필드의 레이블 태그 #}
    {{ form_field|add_label_class:"form-label" }}<br/>

    {# 각 필드의 위젯 렌더링은 템플릿에서 수정할 수 없습니다. #}
    {{ form_field|add_class:"form-control" }}
    {# 각 폼 필드의 입력 도움말 #}
    <div class="form-text text-success">{{ form_field.help_text }}</div>
    <div class="form-text text-danger">
        {# 각 폼 필드의 에러 내역을 렌더링 #}
        {% for error in form_field.errors %}
            {{ error }}<br/>
        {% endfor %}
    </div>
</div>

mydjango04/blog/templates/blog/memo_form.html
<h2>메모 그룹 : {{ memo_group.name }}</h2>

{% if messages %}
    <ul>
        {% for message in messages %}
            <li>[{{ message.tags }}] {{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{{ formset.media }}

<form action="" method="post" novalidate>
    {% csrf_token %}

    {{ formset.management_form }}

    {{ formset.non_form_errors }}

    {% for form in formset %}
        <table>{{ form.as_table }}</table>
    {% endfor %}

    <input type="submit" />
</form>

mydjango04/blog/templates/blog/post_list.html
{# blog/templates/blog/post_list.html #}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>블로그</title>

    {# Minimal CSS Framework #}
    {# https://picocss.com/docs/ or https://andybrewer.github.io/mvp/ #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">

</head>
<body>

<main class="container">
    <section>
        <h2>블로그 포스팅</h2>

        <form action="" method="get">
            <input type="text" name="query" value="{{ query }}"
                   placeholder="검색어를 입력해주세요."/>
            <input type="submit" value="검색"/>
        </form>

        <form action="/blog/new/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="message"
                   placeholder="메시지를 입력해주세요.">
            <input type="file" name="photo" placeholder="사진"/>
            <input type="submit" value="저장하기"/>
        </form>

        <table>
            {% for post in post_list %}
                <tr>
                    <td>{{ post.title }}</td>
                    <td>{{ post.author.username }}</td>
                    <td>
                        {% for tag in post.tag_set.all %}
                            <mark>{{ tag.name }}</mark>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </section>
</main>

</body>
</html>

mydjango04/blog/templates/blog/post_new.html
{{ errors }}

<hr />
request.GET: {{ request.GET }}<br/>
request.POST: {{ request.POST }}<br/>
request.FILES: {{ request.FILES }}<br/>

mydjango04/blog/templates/blog/review_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <h2>{{ review }}</h2>

    <hr />
    <a href="{% url 'blog:review_list' %}">List</a>
    <a href="{% url 'blog:review_edit' review.pk %}">Edit</a>

</body>
</html>

mydjango04/blog/templates/blog/review_form.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Review Form</title>

    {{ form.media }}
</head>
<body>

    <h2>Review Form</h2>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>

</body>
</html>

mydjango04/blog/templates/blog/review_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <h2>Review List</h2>

    <ul>
    {% for review in review_list %}
        <li>
            <a href="{{ review.get_absolute_url }}">
                {{ review }}
            </a>
        </li>
    {% endfor %}
    </ul>

    <hr>
    <a href="{% url 'blog:review_new' %}">New</a>

</body>
</html>

mydjango04/blog/templates/blog/search.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>검색결과</title>
</head>
<body>

{% if not query %}
    <p>입력된 검색어가 없습니다.</p>
{% else %}
    <p>검색어는 "{{ query }}" 입니다.</p>
{% endif %}

<hr />
request.GET: {{ request.GET }}<br/>
request.POST: {{ request.POST }}<br/>
request.FILES: {{ request.FILES }}<br/>

</body>
</html>

mydjango04/blog/templates/blog/tag_form.html
{# blog/templates/blog/tag_form.html #}

{% extends "blog/base.html" %}

{% block title %}태그 폼{% endblock %}

{% block content %}
    <h2>태그 폼</h2>
    {% include "blog/_tag_form.html" %}
{% endblock %}

mydjango04/blog/templates/blog/tag_list.html
{# blog/templates/blog/tag_list.html #}
{% extends "blog/base.html" %}
{% load django_bootstrap5 %}

{% block title %}태그 목록{% endblock %}

{% block content %}
    <h2>태그 목록</h2>

    <button class="btn btn-primary"
            hx-get="{% url 'blog:tag_new' %}"
            hx-get-with-timestamp
            hx-trigger="click"
            hx-target="#modal-container"
            hx-swap="innerHTML"
    >
        새 태그
    </button>


    <button class="btn btn-primary my-3"
            hx-get="{% url 'blog:tag_list' %}?page={{ request.GET.page|default:1 }}"
            hx-get-with-timestamp
            hx-target="#tag-list-container .list-group"
            hx-trigger="click, refresh-tag-list from:body"
            hx-swap="innerHTML transition:true"
    >새로고침
    </button>

    <div class="position-relative">
        <input type="text" name="query" class="form-control my-3"
               hx-get="{% url 'blog:tag_list' %}"
               hx-get-with-timestamp
               hx-trigger="keyup[target.value.length === 0 || target.value.length >= 2] changed delay:400ms"
               hx-target="#tag-list-container .list-group"
               hx-swap="innerHTML transition:true"
               hx-indicator="#tag-list-query-indicator"
        />

        {# indicator가 사용될 때에는 .htmx-request가 적용됩니다. #}
        <div id="tag-list-query-indicator" class="htmx-indicator">
            {# ref: https://getbootstrap.com/docs/5.3/components/spinners/#growing-spinner #}
            <div class="spinner-grow text-primary"
                 style="width: 20px; height: 20px; position: absolute; top: 50%; margin-top: -10px; right: 10px;">
            </div>
        </div>
    </div>


    <div id="tag-list-container">
        <div class="list-group">
            {% include "blog/_tag_list.html" %}
        </div>
    </div>

    <hr/>
    <a href="{% url 'blog:tag_new' %}">새 태그</a>
{% endblock %}