myproj/blog/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

from . import views
from . import api
from .api import PostModelViewSet, TodoViewSet

router = DefaultRouter()
router.register(prefix="posts", viewset=PostModelViewSet)
router.register(prefix="todos", viewset=TodoViewSet)


urlpatterns = [
    # path("", TemplateView.as_view(template_name="blog/index.html"), name="index"),
    path("", views.index, name="index"),
    path("whoami/", views.whoami, name="whoami"),
    path("todos/new/", views.todo_new, name="todo_new"),
    path("todos/<int:pk>/edit/", views.todo_edit, name="todo_edit"),
]
urlpatterns_api_v1 = []
urlpatterns_api_v1 += router.urls

# urlpatterns_api_v1 = [
#     path("", api.post_list, name="post_list"),
#     path("<int:pk>/", api.post_detail, name="post_detail"),
#     path("new/", api.post_list, name="post_new"),
#     path("<int:pk>/edit/", api.post_detail, name="post_edit"),
#     path("<int:pk>/delete/", api.post_detail, name="post_delete"),
# ]

urlpatterns += [
    path("api/", include((urlpatterns_api_v1, "api-v1"))),
]

myproj/mysite/urls.py
from django.apps import apps
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

# from django_nextjs.render import render_nextjs_page


# async def root(request):
#     return await render_nextjs_page(request)


def test(request):
    return render(request, "test.html")


urlpatterns = [
    # path("", root),
    path("test/", test),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("blog/", include("blog.urls")),
    path("", include("photolog.urls")),
    path("", include("core.urls")),
    path("", include("django_components.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if apps.is_installed("debug_toolbar"):
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

myproj/studio/urls.py
from django.urls import path
from . import views

app_name = "studio"

urlpatterns = [
    path("", views.index, name="index"),
    path("following-users/", views.following_users, name="following_users"),
    path("discover-users/", views.discover_users, name="discover_users"),
    path("@<username>/", views.user_page, name="user_page"),
    path(
        "@<username>/follow/",
        views.user_follow,
        name="user_follow",
        kwargs={"action": "follow"},
    ),
    path(
        "@<username>/unfollow/",
        views.user_follow,
        name="user_unfollow",
        kwargs={"action": "unfollow"},
    ),
    path("notes/new/", views.note_new, name="note_new"),
    path("notes/<int:pk>/", views.note_detail, name="note_detail"),
    path("notes/<int:pk>/edit/", views.note_edit, name="note_edit"),
    path(
        "notes/<int:pk>/like/",
        views.note_like,
        name="note_like",
        kwargs={"action": "like"},
    ),
    path(
        "notes/<int:pk>/like/cancel/",
        views.note_like,
        name="note_like_cancel",
        kwargs={"action": "cancel"},
    ),
    path("notes/<int:note_pk>/comments/", views.comment_list, name="comment_list"),
    path("notes/<int:note_pk>/comments/new/", views.comment_new, name="comment_new"),
    path(
        "notes/<int:note_pk>/comments/<int:pk>/edit/",
        views.comment_edit,
        name="comment_edit",
    ),
    path(
        "notes/<int:note_pk>/comments/<int:pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
]

myproj/studio/models.py
import re
from os.path import normpath, splitext
from typing import List
from uuid import uuid4

from PIL import Image
from django.core.files import File
from django.core.files.base import ContentFile
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import force_str
from django_lifecycle import hook, AFTER_SAVE, LifecycleModelMixin
from taggit.managers import TaggableManager

from accounts.models import User


class Note(LifecycleModelMixin, models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager()
    like_user_set = models.ManyToManyField(
        User, related_name="liked_note_set", blank=True
    )

    class Meta:
        ordering = ["-pk"]

    def get_absolute_url(self) -> str:
        return reverse("studio:note_detail", args=[self.pk])

    def is_liked(self, user: User) -> bool:
        return self.like_user_set.filter(id=user.id).exists()

    def like(self, user: User) -> None:
        self.like_user_set.add(user)

    def cancel(self, user: User) -> None:
        self.like_user_set.remove(user)

    def likes_count(self) -> int:
        return self.like_user_set.count()

    @hook(AFTER_SAVE, when="content", has_changed=True)
    def on_saved(self):
        hashtags: List[str] = re.findall(r"#(\w+)", self.content)
        self.tags.set(hashtags, clear=True)


def uuid_name_upload_to(instance: models.Model, filename: str) -> str:
    app_label = instance.__class__._meta.app_label
    cls_name = instance.__class__.__name__.lower()
    ymd_path = normpath(force_str(timezone.now().strftime("%Y/%m/%d")))
    extension = splitext(filename)[-1].lower()
    new_filename = uuid4().hex + extension
    return "/".join((app_label, cls_name, ymd_path, new_filename))


class Photo(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to=uuid_name_upload_to,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def make_thumb(cls, file: File, max_width, max_height) -> File:
        pil_image = Image.open(file)
        pil_image.thumbnail((max_width, max_height))
        if pil_image.mode == "RGBA":
            pil_image = pil_image.convert("RGBA")

        thumb_name = splitext(file.name)[0] + ".jpg"
        thumb_file = ContentFile(b"", name=thumb_name)
        pil_image.save(thumb_file)

        return thumb_file

    @classmethod
    def create_photos(cls, note: Note, photo_file_list: List[File]) -> List["Photo"]:
        if not note.pk:
            raise ValueError("Note를 먼저 저장해주세요.")

        photo_list = []
        for photo_file in photo_file_list:
            photo = cls(note=note)
            photo.image.save(photo_file.name, photo_file, save=False)
            photo_list.append(photo)

        Photo.objects.bulk_create(photo_list)

        return photo_list


class Comment(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-pk"]

myproj/studio/views.py
from typing import Literal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet, Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)
from django_htmx.http import trigger_client_event

from accounts.models import User
from core.decorators import login_required_hx
from studio.forms import (
    NoteCreateForm,
    PhotoUpdateFormSet,
    NoteUpdateForm,
    CommentForm,
)
from studio.models import Note, Photo, Comment


def index(request):
    if not request.user.is_authenticated:
        note_qs = Note.objects
    else:
        user: User = request.user
        note_qs = Note.objects.filter(
            Q(author=user) | Q(author__in=user.following_user_set.all())
        )

    query = request.GET.get("query", "").strip()
    if query:
        note_qs = note_qs.filter(
            Q(title__icontains=query) | Q(author__username=query),
        )

    tag_name = request.GET.get("tag", "").strip()
    if tag_name:
        note_qs = note_qs.filter(tags__name__in=[tag_name])

    note_qs = note_qs.select_related("author").prefetch_related("photo_set", "tags")

    return render(
        request,
        "studio/index.html",
        {
            "note_list": note_qs,
            "query": query,
        },
    )


@login_required
def following_users(request):
    user: User = request.user
    user_qs = user.following_user_set.exclude(id__in=[user.pk]).select_related(
        "profile"
    )
    return render(
        request,
        "studio/user_list.html",
        {
            "user_list": user_qs,
            "button_type": "unfollow",
        },
    )


@login_required
def discover_users(request):
    user: User = request.user
    user_qs = User.objects.exclude(id__in=user.following_user_set.all()).select_related(
        "profile"
    )
    return render(
        request,
        "studio/user_list.html",
        {
            "user_list": user_qs,
            "button_type": "following",
        },
    )


def user_page(request, username):
    author = get_object_or_404(User, is_active=True, username=username)

    note_qs = (
        Note.objects.filter(author=author)
        .select_related("author")
        .prefetch_related("photo_set", "tags")
    )

    if request.user.is_authenticated:
        user: User = request.user
        is_follower = user.is_follower(author)
    else:
        is_follower = False

    return render(
        request,
        "studio/user_page.html",
        {
            "author": author,
            "note_list": note_qs,
            "follower_button": {
                "is_follower": is_follower,
                "follower_count": author.follower_count(),
            },
        },
    )


@login_required_hx
def user_follow(request, username, action: Literal["follow", "unfollow"]):
    from_user: User = request.user
    to_user = get_object_or_404(User, is_active=True, username=username)
    if action == "follow":
        messages.success(request, f"{username}님을 팔로잉했습니다.")
        from_user.follow(to_user)
    else:
        messages.success(request, f"{username}님을 언팔했습니다.")
        from_user.unfollow(to_user)

    if request.htmx:
        return render(
            request,
            "studio/_user_following_button.html",
            {
                "author": to_user,
                "is_follower": from_user.is_follower(to_user),
                "follower_count": to_user.follower_count(),
            },
        )

    return redirect("studio:user_page", username)


class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    form_class = NoteCreateForm
    template_name = "crispy_form.html"
    extra_context = {"form_title": "기록 남기기"}

    def form_valid(self, form):
        # get_success_url 내의 format 문자열 조합을 위해 필요
        self.object = form.save(commit=False)

        note = self.object
        note.author = self.request.user
        note.save()

        photo_file_list = form.cleaned_data.get("photos")
        if photo_file_list:
            Photo.create_photos(note, photo_file_list)

        messages.success(self.request, "새로운 노트를 저장했습니다.")

        return redirect(note)


note_new = NoteCreateView.as_view()


@login_required
def note_edit(request, pk):
    note = get_object_or_404(Note, pk=pk)

    photo_qs = Photo.objects.filter(note=note)
    if request.method == "GET":
        note_form = NoteUpdateForm(instance=note, prefix="note")
        photo_formset = PhotoUpdateFormSet(
            queryset=photo_qs,
            instance=note,
            prefix="photos",
        )
    else:
        note_form = NoteUpdateForm(
            data=request.POST,
            files=request.FILES,
            instance=note,
            prefix="note",
        )
        photo_formset = PhotoUpdateFormSet(
            data=request.POST,
            files=request.FILES,
            queryset=photo_qs,
            instance=note,
            prefix="photos",
        )
        if note_form.is_valid() and photo_formset.is_valid():
            note_form.save()

            photo_file_list = note_form.cleaned_data.get("photos")
            if photo_file_list:
                Photo.create_photos(note, photo_file_list)

            photo_formset.save()

            messages.success(request, f"노트#{pk}을(를) 수정했습니다.")
            return redirect(note)

    return render(
        request,
        "crispy_form_and_formset.html",
        {
            "form_title": "노트 수정",
            "form_submit_label": "저장하기",
            "form": note_form,
            "formset": photo_formset,
        },
    )


@login_required_hx
def note_like(request, pk, action: Literal["like", "cancel"]):
    note = get_object_or_404(Note, pk=pk)
    if action == "like":
        note.like(request.user)
    else:
        note.cancel(request.user)

    if request.htmx:
        return render(
            request,
            "studio/_note_like_button.html",
            {
                "note": note,
                "is_liked": note.is_liked(request.user),
                "count": note.likes_count(),
            },
        )
        return
    return redirect(note)


class NoteDetailView(DetailView):
    model = Note

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        note = self.object
        context_data["like_button"] = {
            "is_liked": note.is_liked(self.request.user),
            "count": note.likes_count(),
        }
        context_data["comment_list"] = note.comment_set.select_related(
            "author__profile"
        )
        return context_data


note_detail = NoteDetailView.as_view()


class CommentListView(ListView):
    template_name = "studio/_comment_list.html"

    def get_queryset(self) -> QuerySet[Comment]:
        note_pk = self.kwargs["note_pk"]
        return Comment.objects.filter(note__pk=note_pk).select_related(
            "author__profile"
        )


comment_list = CommentListView.as_view()


# 함수 장식자로도 클래스 기반 뷰에 적용 가능


@method_decorator(login_required_hx, name="dispatch")
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = "studio/_comment_form.html"

    def dispatch(self, request, *args, **kwargs):
        self.note = get_object_or_404(Note, pk=kwargs["note_pk"])  # noqa
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.note = self.note
        comment.author = self.request.user
        comment.save()

        messages.success(self.request, "태그를 저장했습니다.")
        response = render(self.request, "_messages_as_event.html")
        response = trigger_client_event(response, "refresh-comment-list")
        return response


comment_new = CommentCreateView.as_view()


@method_decorator(login_required_hx, name="dispatch")
class CommentUpdateView(UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "studio/_comment_form.html"

    def get_queryset(self):
        note_pk = self.kwargs["note_pk"]
        qs = super().get_queryset()
        qs = qs.filter(note__pk=note_pk, author=self.request.user)
        return qs

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "태그를 저장했습니다.")
        response = render(self.request, "_messages_as_event.html")
        response = trigger_client_event(response, "refresh-comment-list")
        return response


comment_edit = CommentUpdateView.as_view()


@method_decorator(login_required_hx, name="dispatch")
class CommentDeleteView(DeleteView):
    model = Comment

    def get_queryset(self):
        note_pk = self.kwargs["note_pk"]
        qs = super().get_queryset()
        qs = qs.filter(note__pk=note_pk, author=self.request.user)
        return qs

    def form_valid(self, form):
        self.object.delete()
        messages.success(self.request, "태그를 삭제했습니다.")
        response = render(self.request, "_messages_as_event.html")
        response = trigger_client_event(response, "refresh-comment-list")
        return response


comment_delete = CommentDeleteView.as_view()

myproj/studio/templates/studio/_comment_form.html
{% load component_tags crispy_forms_tags partials %}

{% include "_messages_as_event.html" %}

{% partialdef form %}
    <form hx-post="{{ request.get_full_path }}"
          hx-trigger="submit once"
          hx-swap="outerHTML"
          autocomplete="off"
          novalidate>
        {% crispy form %}
    </form>
{% endpartialdef %}

{% if request.method == "POST" %}
    {% partial form %}
{% else %}
    {% component "modal-form"%}
        {% fill "modal-title" %}
            {% if not form.instance.pk %}새 댓글{% else %}댓글 수정{% endif %}
        {% endfill %}
        {% fill "modal-body" %}
            {% partial form %}
        {% endfill %}
    {% endcomponent %}
    <script>
      (function() {
        const modalEl = document.currentScript.previousElementSibling;
        document.body.addEventListener("refresh-comment-list", () => {
          htmx.trigger(modalEl, "hide");
        });
      })();
    </script>
{% endif %}

myproj/studio/templates/studio/_comment_list.html
{% load i18n %}

{% for comment in comment_list %}
    {# refs: https://bbbootstrap.com/snippets/bootstrap-5-user-comment-section-template-46707409 #}
    <div class="d-flex flex-row p-3">
        <img src="{{ comment.author.profile.avatar.url }}"
             width="60" height="60"
             class="rounded-circle me-3"
             alt="{{ comment.author }}'s Avatar"/>

        <div class="w-100">
            <div class="d-flex flex-row align-items-center">
                <span class="me-3">{{ comment.author.username }}</span>
                {# <small class="badge text-bg-primary me-3">Top Comment</small> #}
                {% language "en-us" %}
                    <small class="text-muted">{{ comment.created_at|timesince }} ago</small>
                {% endlanguage %}
            </div>

            <div class="mb-1">
                {{ comment.message|linebreaks }}
            </div>

            <div class="d-flex flex-row">
                 {# <span class="me-3"><i class="bi bi-heart me-2"></i>0</span> #}
                 {# <span class="me-3"><i class="bi bi-wechat me-2"></i>Reply</span> #}

                {% if user == comment.author %}
                    <a href="#"
                       hx-get="{% url 'studio:comment_edit' comment.note.pk comment.pk %}"
                       hx-get-with-timestamp
                       hx-target="body"
                       hx-swap="beforeend"  {# body 내용 끝에 추가 #}
                       class="me-3 text-white text-decoration-none"><i class="bi bi-pencil"></i> 수정하기</a>

                    <a href="#"
                       hx-post="{% url 'studio:comment_delete' comment.note.pk comment.pk %}"
                       hx-confirm="Are you sure?"
                       hx-swap="none"
                       class="text-white text-decoration-none"><i class="bi bi-trash"></i> 삭제하기</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endfor %}

myproj/studio/templates/studio/_note_like_button.html
{% if is_liked %}
    <a href="{% url 'studio:note_like_cancel' note.pk %}"
       hx-post="{% url 'studio:note_like_cancel' note.pk %}"
       hx-swap="outerHTML"
       class="btn btn-warning">
        <i class="bi bi-heart-fill me-2"></i>
        {{ count }}
    </a>
{% else %}
    <a href="{% url 'studio:note_like' note.pk %}"
       hx-post="{% url 'studio:note_like' note.pk %}"
       hx-swap="outerHTML"
       class="btn btn-warning">
        <i class="bi bi-heart me-2"></i>
        {{ count }}
    </a>
{% endif %}

myproj/studio/templates/studio/_note_list.html
{% load component_tags %}

<div class="container">
    <div class="row">
        {% for note in note_list %}
            {# target="_blank" #}
            {% component "image-overlay" class="col-xl-3 col-lg-4 col-md-6 mt-4" %}
                {% fill "link" %}{{ note.get_absolute_url }}{% endfill %}
                {# first를 사용하면, 캐시를 사용할 수 없습니다. #}
                {% fill "img-src" %}{{ note.photo_set.all.0.image.url }}{% endfill %}
                {% fill "text" %}
                    {{ note.title }}<br/>by {{ note.author.username }}
                    <small class="d-block mt-3 text-muted">
                        {% for name in note.tags.all %}
                            #{{ name }}
                        {% endfor %}
                    </small>
                {% endfill %}
            {% endcomponent %}
        {% endfor %}
    </div>
</div>

myproj/studio/templates/studio/_user_following_button.html
{% include "_messages_as_event.html" %}

{% if is_follower %}
    <a href="{% url 'studio:user_unfollow' author.username %}"
       hx-post="{% url 'studio:user_unfollow' author.username %}"
       hx-swap="outerHTML"
       class="btn btn-sm btn-primary">
        <i class="bi bi-person-check-fill"></i>
        팔로잉
    </a>
{% else %}
    <a href="{% url 'studio:user_follow' author.username %}"
       hx-post="{% url 'studio:user_follow' author.username %}"
       hx-swap="outerHTML"
       class="btn btn-sm btn-secondary">
        <i class="bi bi-person-add"></i>
        팔로잉 하기
    </a>
{% endif %}

myproj/studio/templates/studio/base.html
{% extends "base.html" %}

{% block content %}
    {% block studio-content %}
    {% endblock %}
{% endblock %}

myproj/studio/templates/studio/index.html
{% extends "studio/base.html" %}
{% load static component_tags %}

{% block studio-content %}
    {% include "studio/_note_list.html" %}
{% endblock %}

myproj/studio/templates/studio/note_detail.html
{% extends "studio/base.html" %}
{% load component_tags i18n %}

{% block studio-content %}
    <div class="card">
        <div class="card-header">
            <div class="d-flex flex-row gap-2">
                {% if note.author.profile.avatar %}
                    <img src="{{ note.author.profile.avatar.url }}"
                         class="rounded-circle"
                         style="width: 40px; height: 40px;"
                         alt=""/>
                {% endif %}
                <div class="w-100">
                    <div class="d-flex flex-column">
                        <a href="{% url 'studio:user_page' note.author.username %}" class="me-3">{{ note.author.username }}</a>
                        {% language "en-us" %}
                            <small class="text-muted">{{ note.created_at|timesince }} ago</small>
                        {% endlanguage %}
                    </div>
                </div>
            </div>

        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <h4>{{ note.title }}</h4>
                    <div data-hashtag-linkify="{% url 'studio:index' %}?tag=">
                        {{ note.content|linebreaks }}
                    </div>
                </div>
                <div class="col-md-6">
                    {% component "carousel" note.photo_set.all attr_name="image.url" %}{% endcomponent %}
                </div>
            </div>
        </div>
    </div>

    <div class="my-3 d-flex flex-row gap-3">
        <a href="{% url 'studio:index' %}" class="btn btn-primary">목록으로</a>
        <a href="{% url 'studio:note_edit' note.pk %}" class="btn btn-success">수정하기</a>

        {# 비로그인 상태에서는 클릭하면 로그인 페이지로 이동합니다. #}
        {% include "studio/_note_like_button.html" with note=note is_liked=like_button.is_liked count=like_button.count only %}
    </div>

    <div class="my-3">
        <button hx-get="{% url 'studio:comment_new' note.pk %}"
                hx-get-with-timestamp
                hx-target="body"
                hx-swap="beforeend"  {# body 내용 끝에 추가 #}
                class="btn btn-primary w-100">댓글 작성하기
        </button>
    </div>

    <div id="comment-list">
        {% include "studio/_comment_list.html" %}
    </div>

    <div class="my-3">
        <button hx-get="{% url 'studio:comment_list' note.pk %}"
                hx-get-with-timestamp
                hx-trigger="click, refresh-comment-list from:body"
                hx-target="#comment-list"
                class="btn btn-primary w-100">댓글 새로고침
        </button>
    </div>
{% endblock %}

myproj/studio/templates/studio/user_list.html
{% extends "studio/base.html" %}

{% block studio-content %}
    <div class="row">
        {% for user in user_list %}
            <div class="col-xl-3 col-lg-4 col-md-6 mt-4">
                <div class="card h-100">
                    <div class="card-header">
                        <div class="d-flex flex-row align-items-center gap-2">
                            {% if user.profile.avatar %}
                                <img src="{{ request.user.profile.avatar.url }}"
                                     alt=""
                                     style="width: 32px; height: 32px;"
                                     class="rounded-circle"
                                />
                            {% else %}
                                <i class="bi bi-person-circle" style="font-size: 1.6rem;"></i>
                            {% endif %}
                            <a href="{% url 'studio:user_page' user.username %}"
                               style="text-decoration: none; color: inherit;">
                                {{ user.username }}
                            </a>
                        </div>
                    </div>
                    <div class="card-body" style="font-size: 0.8rem;">
                        {% if user.profile.bio %}
                            {{ user.profile.bio|linebreaks }}
                        {% else %}
                            <span class="text-muted">자기 소개가 없어요.</span>
                        {% endif %}
                    </div>
                    <div class="card-footer text-end">
                        {% if button_type == "following" %}
                            <a href="{% url 'studio:user_follow' user.username %}"
                               class="btn btn-secondary btn-sm">
                                <i class="bi bi-plus-circle-fill"></i>
                                팔로잉하기
                            </a>
                        {% else %}
                            <a href="{% url 'studio:user_follow' user.username %}"
                               class="btn btn-primary btn-sm">
                                <i class="bi bi-dash-circle-fill"></i>
                                언팔하기
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

myproj/studio/templates/studio/user_page.html
{% extends "studio/base.html" %}
{% load static component_tags %}

{% block studio-content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                {% if author.profile.avatar %}
                    <img src="{{ author.profile.avatar.url }}" class="rounded-circle"
                         alt="{{ author.username }}'s Avatar"
                         style="width: 128px;"
                    />
                {% endif %}

                <h2 class="my-3">@{{ author.username }}</h2>

                {% include "studio/_user_following_button.html" with author=author is_follower=follower_button.is_follower follower_count=follower_button.follower_count only %}
            </div>
        </div>
    </div>

    {% include "studio/_note_list.html" %}
{% endblock %}