mydjango04/hottrack/urls.py
from django.urls import path, re_path
from . import converters  # noqa
from . import views

app_name = "hottrack"

urlpatterns = [
    path(route="", view=views.index, name="index"),
    path(route="<int:pk>/", view=views.song_detail, name="song_detail"),
    # Song 모델에서 melon_uid 필드를 id 기본키로 변경했기에 melon_uid 인자 지원이 필요없어졌습니다.
    re_path(
        route=r"^export\.(?P<format>(csv|xlsx))$", view=views.export, name="export"
    ),
    path(route="<int:pk>/cover.png", view=views.cover_png, name="cover_png"),
    path(
        route="archives/<int:year>/",
        view=views.SongYearArchiveView.as_view(),
        name="song_archive_year",
    ),
    path(
        route="archives/<int:year>/<int:month>/",
        view=views.SongMonthArchiveView.as_view(),
        name="song_archive_month",
    ),
    path(
        route="archives/<int:year>/<int:month>/<int:day>/",
        view=views.SongDayArchiveView.as_view(),
        name="song_archive_day",
    ),
    path(
        route="archives/today/",
        view=views.SongTodayArchiveView.as_view(),
        name="song_archive_today",
    ),
    path(
        route="archives/<int:year>/week/<int:week>/",
        view=views.SongWeekArchiveView.as_view(),
        name="song_archive_week",
    ),
    re_path(
        route=r"^archives/(?P<date_list_period>year|month|day|week)?/?$",
        view=views.SongArchiveIndexView.as_view(),
        name="song_archive_index",
    ),
    re_path(
        route=r"^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<slug>[-\w]+)/$",
        view=views.SongDateDetailView.as_view(),
        name="song_detail",  # 앞서 위치한 song_detail과 같은 이름이지만, 인자 구성이 다릅니다.
    ),
]

mydjango04/hottrack/templates/hottrack/_pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; 처음으로</a>
            <a href="?page={{ page_obj.previous_page_number }}">이전페이지</a>
        {% endif %}

        <span class="current">
            현재 {{ page_obj.number }}페이지 (전체: {{ page_obj.paginator.num_pages }})
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">다음페이지</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">마지막으로</a>
        {% endif %}
    </span>
</div>

mydjango04/hottrack/templates/hottrack/_song.html
{# 경로 : hottrack/templates/hottrack/_song.html #}

<div class="card shadow-sm">
    {# refs: https://picsum.photos/ #}
    <img src="{{ song.cover_url }}" alt="{{ song.name }}" class="cart-img-top" />

    <div class="card-body">
        <p class="card-text">
            <div class="text-nowrap overflow-hidden text-truncate">{{ song.artist.name }} | {{ song.name }}</div>
        </p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a href="{{ song.get_absolute_url }}"
                   class="btn btn-sm btn-outline-primary">Detail</a>
                {# Song 모델에서 melon_uid 필드를 id 기본키로 변경했기에 melon_uid 인자 지원이 필요없어졌습니다. #}
                <a href="{{ song.melon_detail_url }}" type="button" class="btn btn-sm btn-outline-danger">Melon</a>
                <a href="{{ song.youtube_search_url }}" type="button" class="btn btn-sm btn-outline-danger">Youtube</a>
            </div>
            <small class="text-body-secondary">
                {{ song.like_count }}
            </small>
        </div>
    </div>
</div>

mydjango04/hottrack/templates/hottrack/base.html
{# hottrack/templates/hottrack/base.html #}

{# 간략히 구현했지만 hottrack/templates/hottrack/index.html 레이아웃을 적용하기를 권장 #}

{% load django_bootstrap5 %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>hottrack</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

<div class="container">
    {% block content %}{% endblock %}
</div>

</body>
</html>

mydjango04/hottrack/templates/hottrack/index.html
{% load django_bootstrap5 %}

{# 경로 : hottrack/templates/hottrack/index.html #}

<!doctype html>
<html lang="ko" data-bs-theme="dark">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>HotTrack</title>

    {# https://cdnjs.com/libraries/bootstrap #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/js/bootstrap.bundle.min.js"></script>

</head>
<body>

{# ref: https://getbootstrap.com/docs/5.3/examples/album/ #}

<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>About</h4>
                    <p class="text-body-secondary">Add some information about the album below, the author, or any other
                        background context. Make it a few sentences long so folks can pick up some informative tidbits.
                        Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4>계정</h4>
                    <ul class="list-unstyled">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:login' %}?next={{ request.path }}" class="text-white">로그인</a></li>
                            <li><a href="{% url 'accounts:signup' %}?next={{ request.path }}" class="text-white">회원가입</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:profile' %}" class="text-white">프로필</a></li>
                            <li>
                                <form action="{% url 'accounts:logout' %}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.path }}" />
                                    <button type="submit" class="btn btn-link text-white p-0">로그아웃</button>
                                </form>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>HotTrack</strong>
            </a>

            <form action="" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark text-bg-dark"
                       placeholder="검색어를 입력해주세요."
                       name="query"
                       value="{{ request.GET.query }}"
                       {# value="{{ query }}" #}
                />
            </form>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">HotTrack</h1>
                <p class="lead text-body-secondary">
                    HotTrack에서 최신 K-POP 트렌드를 한 눈에! 실시간 차트, 뜨거운 뮤직 비디오, 가장 핫한 아티스트까지, K-POP의 모든 것을 만나보세요.
                </p>
                <p>
                    <a href="#" class="btn btn-primary my-2">Signup</a>
                    <a href="#" class="btn btn-secondary my-2">Login</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for song in song_list %}
                    <div class="col">
                        {% include "hottrack/_song.html" with song=song only %}
                    </div>
                {% endfor %}
            </div>

            {# include "hottrack/_pagination.html" with page_obj=page_obj only #}
            <div class="my-5 d-flex justify-content-center">
                {% bootstrap_pagination page_obj %}
            </div>
        </div>
    </div>

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>

</body>
</html>

mydjango04/hottrack/templates/hottrack/song_archive.html
{# hottrack/song_archive.html #}

{% extends "hottrack/base.html" %}
{% load django_bootstrap5 %}

{% block content %}

<div class="p-3 d-flex gap-3">
    <div>
        <h2>{{ date_list_period|title }} Index</h2>

        <ul>
            {% for song in latest %}
                <li>
                    {{ song.name|truncatechars:20 }}
                    <small class="text-secondary fw-light">{{ song.release_date|date:"Y년 m월 d일" }}</small>
                </li>
            {% endfor %}
        </ul>

        {% if page_obj %}{% bootstrap_pagination page_obj %}{% endif %}
    </div>
    <div>
        <h3>{{ date_list_period|title }} 목록</h3>
        <ul>
            {% for date in date_list %}
                <li>
                    {% if date_list_period == "year" %}
                        <a href="{% url 'hottrack:song_archive_year' date.year %}">
                            {{ date|date:"Y년" }}
                        </a>
                    {% elif date_list_period == "month" %}
                        <a href="{% url 'hottrack:song_archive_month' date.year date.month %}">
                            {{ date|date:"Y년 m월" }}
                        </a>
                    {% elif date_list_period == "day" %}
                        <a href="{% url 'hottrack:song_archive_day' date.year date.month date.day %}">
                            {{ date|date:"Y년 m월 d일" }}
                        </a>
                    {% elif date_list_period == "week" %}
                        <a href="{% url 'hottrack:song_archive_week' date.year date.isocalendar.week %}">
                            {{ date|date:"Y년 W주" }}
                        </a>
                    {% else %}
                        <div class="alert alert-danger">Invalid date_list_period : {{ date_list_period }}</div>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

mydjango04/hottrack/templates/hottrack/song_archive_day.html
{# hottrack/song_archive_day.html #}

{% extends "hottrack/base.html" %}

{% block content %}

    <div class="p-3 d-flex gap-3">
        <div>
            <h2>{{ day|date:"Y년 m월 d일" }}</h2>

            <div class="text-center">
                <div class="btn-group">
                    {% if previous_day %}
                        <a href="{% url 'hottrack:song_archive_day' previous_day.year previous_day.month previous_day.day %}"
                           class="btn btn-outline-primary">
                            {{ previous_day|date:"Y년 m월 d일" }}
                        </a>
                    {% endif %}
                    {% if next_day %}
                        <a href="{% url 'hottrack:song_archive_day' next_day.year next_day.month next_day.day %}"
                           class="btn btn-outline-primary">
                            {{ next_day|date:"Y년 m월 d일" }}
                        </a>
                    {% endif %}
                </div>
            </div>

            <ul>
                {% for song in song_list %}
                    <li>
                        {{ song.name|truncatechars:20 }}
                        <small class="text-secondary fw-light">{{ song.release_date|date:"Y년 m월 d일" }}</small>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h3>Nav</h3>
            <div class="alert alert-info">
                지난/다음 달 context data를 지원
            </div>
            <div class="btn-group d-flex w-100">
                {% if previous_month %}
                    <a href="{% url 'hottrack:song_archive_month' previous_month.year previous_month.month %}"
                       class="btn btn-primary">
                        지난 달
                    </a>
                {% endif %}
                {% if next_month %}
                    <a href="{% url 'hottrack:song_archive_month' next_month.year next_month.month %}"
                       class="btn btn-primary">
                        다음 달
                    </a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

mydjango04/hottrack/templates/hottrack/song_archive_month.html
{# hottrack/song_archive_month.html #}

{% extends "hottrack/base.html" %}

{% block content %}

    <div class="p-3 d-flex gap-3">
        <div>
            <h2>{{ month|date:"Y년 m월" }}</h2>

            <div class="text-center">
                <div class="btn-group">
                    {% if previous_month %}
                        <a href="{% url 'hottrack:song_archive_month' previous_month.year previous_month.month %}"
                           class="btn btn-outline-primary">
                            {{ previous_month|date:"Y년 m월" }}
                        </a>
                    {% endif %}
                    {% if next_month %}
                        <a href="{% url 'hottrack:song_archive_month' next_month.year next_month.month %}"
                           class="btn btn-outline-primary">
                            {{ next_month|date:"Y년 m월" }}
                        </a>
                    {% endif %}
                </div>
            </div>

            <ul>
                {% for song in song_list %}
                    <li>
                        {{ song.name|truncatechars:20 }}
                        <small class="text-secondary fw-light">{{ song.release_date|date:"Y년 m월 d일" }}</small>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h3>Nav</h3>
            <ul>
                {% for date in date_list %}
                    <li>
                        <a href="{% url 'hottrack:song_archive_day' date.year date.month date.day %}">
                            {{ date|date:"Y년 m월 d일" }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

mydjango04/hottrack/templates/hottrack/song_archive_week.html
{# hottrack/song_archive_week.html #}

{% extends "hottrack/base.html" %}

{% block content %}

    <div class="p-3 d-flex gap-3">
        <div>
            <h2>{{ week|date:"Y년 W주" }}</h2>

            <div class="text-center">
                <div class="btn-group">
                    {% if previous_week %}
                        <a href="{% url 'hottrack:song_archive_week' previous_week.year previous_week.isocalendar.week %}"
                           class="btn btn-outline-primary">
                            {{ previous_week|date:"Y년 W주" }}
                        </a>
                    {% endif %}
                    {% if next_week %}
                        <a href="{% url 'hottrack:song_archive_week' next_week.year next_week.isocalendar.week %}"
                           class="btn btn-outline-primary">
                            {{ next_week|date:"Y년 W주" }}
                        </a>
                    {% endif %}
                </div>
            </div>

            <ul>
                {% for song in song_list %}
                    <li>
                        {{ song.name|truncatechars:20 }}
                        <small class="text-secondary fw-light">{{ song.release_date|date:"Y년 m월 d일" }}</small>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

mydjango04/hottrack/templates/hottrack/song_archive_year.html
{# hottrack/song_archive_year.html #}

{% extends "hottrack/base.html" %}

{% block content %}

    <div class="p-3 d-flex gap-3">
        <div>
            <h2>{{ year|date:"Y년" }}</h2>

            <div class="text-center">
                <div class="btn-group">
                    {% if previous_year %}
                        <a href="{% url 'hottrack:song_archive_year' previous_year.year %}"
                           class="btn btn-outline-primary">
                            {{ previous_year|date:"Y년" }}
                        </a>
                    {% endif %}
                    {% if next_year %}
                        <a href="{% url 'hottrack:song_archive_year' next_year.year %}"
                           class="btn btn-outline-primary">
                            {{ next_year|date:"Y년" }}
                        </a>
                    {% endif %}
                </div>
            </div>

            <ul>
                {% for song in song_list %}
                    <li>
                        {{ song.name|truncatechars:20 }}
                        <small class="text-secondary fw-light">{{ song.release_date|date:"Y년 m월 d일" }}</small>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <h3>Nav</h3>
            <ul>
                {% for date in date_list %}
                    {# <li>{{ date|date:"Y년 m월" }}</li> #}
                    <li>
                        <a href="{% url 'hottrack:song_archive_month' date.year date.month %}">
                            {{ date|date:"Y년 m월" }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

mydjango04/hottrack/templates/hottrack/song_detail.html
{# 경로 : hottrack/templates/hottrack/index.html #}

<!doctype html>
<html lang="ko" data-bs-theme="dark">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>HotTrack</title>

    {# https://cdnjs.com/libraries/bootstrap #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/js/bootstrap.bundle.min.js"></script>

</head>
<body>

{# ref: https://getbootstrap.com/docs/5.3/examples/album/ #}

<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>About</h4>
                    <p class="text-body-secondary">Add some information about the album below, the author, or any other
                        background context. Make it a few sentences long so folks can pick up some informative tidbits.
                        Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4>Contact</h4>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white">Follow on Twitter</a></li>
                        <li><a href="#" class="text-white">Like on Facebook</a></li>
                        <li><a href="#" class="text-white">Email me</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>HotTrack</strong>
            </a>

            <form action="/hottrack/" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark text-bg-dark"
                       placeholder="검색어를 입력해주세요."
                       name="query"
                       value="{{ request.GET.query }}"
                       {# value="{{ query }}" #}
                />
            </form>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <div class="card bg-dark text-white">
                    <img src="{{ song.cover_url }}" class="card-img-top" alt="Album Cover">
                    <div class="card-body">
                        <h1 class="card-title">{{ song.name }}</h1>
                        <p class="card-text">{{ song.album.name }} - {{ song.artist.name }}</p>
                        <p class="card-text">{{ song.genre }}</p>
                        <p class="card-text">{{ song.release_date }}</p>
                        <p class="card-text"><small class="text-muted">Likes: {{ song.like_count }}</small></p>
                        <div class="btn-group">
                            <a href="{{ song.melon_detail_url }}" type="button" class="btn btn-sm btn-outline-danger">Melon</a>
                            <a href="{{ song.youtube_search_url }}" type="button" class="btn btn-sm btn-outline-danger">Youtube</a>
                        </div>
                    </div>
                </div>
                <p class="lead text-muted mt-3">
                    {{ song.lyrics|linebreaks }}
                </p>
                <p>
                    <a href="#" class="btn btn-primary my-2">Signup</a>
                    <a href="#" class="btn btn-secondary my-2">Login</a>
                </p>
            </div>
        </div>
    </section>
</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>

</body>
</html>